// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rc.proto

package rc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RICControlCellTypeEnum int32

const (
	RICControlCellTypeEnum_RIC_CONTROL_CELL_UNKWON RICControlCellTypeEnum = 0
	RICControlCellTypeEnum_RIC_CONTROL_NR_CELL     RICControlCellTypeEnum = 1
	RICControlCellTypeEnum_RIC_CONTROL_EUTRAN_CELL RICControlCellTypeEnum = 2
)

var RICControlCellTypeEnum_name = map[int32]string{
	0: "RIC_CONTROL_CELL_UNKWON",
	1: "RIC_CONTROL_NR_CELL",
	2: "RIC_CONTROL_EUTRAN_CELL",
}
var RICControlCellTypeEnum_value = map[string]int32{
	"RIC_CONTROL_CELL_UNKWON": 0,
	"RIC_CONTROL_NR_CELL":     1,
	"RIC_CONTROL_EUTRAN_CELL": 2,
}

func (x RICControlCellTypeEnum) String() string {
	return proto.EnumName(RICControlCellTypeEnum_name, int32(x))
}
func (RICControlCellTypeEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_rc_15892e2b949a3eb0, []int{0}
}

type RICControlAckEnum int32

const (
	RICControlAckEnum_RIC_CONTROL_ACK_UNKWON RICControlAckEnum = 0
	RICControlAckEnum_RIC_CONTROL_NO_ACK     RICControlAckEnum = 1
	RICControlAckEnum_RIC_CONTROL_ACK        RICControlAckEnum = 2
	RICControlAckEnum_RIC_CONTROL_NACK       RICControlAckEnum = 3
)

var RICControlAckEnum_name = map[int32]string{
	0: "RIC_CONTROL_ACK_UNKWON",
	1: "RIC_CONTROL_NO_ACK",
	2: "RIC_CONTROL_ACK",
	3: "RIC_CONTROL_NACK",
}
var RICControlAckEnum_value = map[string]int32{
	"RIC_CONTROL_ACK_UNKWON": 0,
	"RIC_CONTROL_NO_ACK":     1,
	"RIC_CONTROL_ACK":        2,
	"RIC_CONTROL_NACK":       3,
}

func (x RICControlAckEnum) String() string {
	return proto.EnumName(RICControlAckEnum_name, int32(x))
}
func (RICControlAckEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_rc_15892e2b949a3eb0, []int{1}
}

type RICE2APHeader struct {
	RanFuncId            int64    `protobuf:"varint,1,opt,name=RanFuncId,proto3" json:"RanFuncId,omitempty"`
	RICRequestorID       int64    `protobuf:"varint,2,opt,name=RICRequestorID,proto3" json:"RICRequestorID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RICE2APHeader) Reset()         { *m = RICE2APHeader{} }
func (m *RICE2APHeader) String() string { return proto.CompactTextString(m) }
func (*RICE2APHeader) ProtoMessage()    {}
func (*RICE2APHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_rc_15892e2b949a3eb0, []int{0}
}
func (m *RICE2APHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RICE2APHeader.Unmarshal(m, b)
}
func (m *RICE2APHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RICE2APHeader.Marshal(b, m, deterministic)
}
func (dst *RICE2APHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RICE2APHeader.Merge(dst, src)
}
func (m *RICE2APHeader) XXX_Size() int {
	return xxx_messageInfo_RICE2APHeader.Size(m)
}
func (m *RICE2APHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_RICE2APHeader.DiscardUnknown(m)
}

var xxx_messageInfo_RICE2APHeader proto.InternalMessageInfo

func (m *RICE2APHeader) GetRanFuncId() int64 {
	if m != nil {
		return m.RanFuncId
	}
	return 0
}

func (m *RICE2APHeader) GetRICRequestorID() int64 {
	if m != nil {
		return m.RICRequestorID
	}
	return 0
}

type RICControlHeader struct {
	ControlStyle         int64    `protobuf:"varint,1,opt,name=ControlStyle,proto3" json:"ControlStyle,omitempty"`
	ControlActionId      int64    `protobuf:"varint,2,opt,name=ControlActionId,proto3" json:"ControlActionId,omitempty"`
	UEID                 *UeId    `protobuf:"bytes,3,opt,name=UEID,proto3" json:"UEID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RICControlHeader) Reset()         { *m = RICControlHeader{} }
func (m *RICControlHeader) String() string { return proto.CompactTextString(m) }
func (*RICControlHeader) ProtoMessage()    {}
func (*RICControlHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_rc_15892e2b949a3eb0, []int{1}
}
func (m *RICControlHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RICControlHeader.Unmarshal(m, b)
}
func (m *RICControlHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RICControlHeader.Marshal(b, m, deterministic)
}
func (dst *RICControlHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RICControlHeader.Merge(dst, src)
}
func (m *RICControlHeader) XXX_Size() int {
	return xxx_messageInfo_RICControlHeader.Size(m)
}
func (m *RICControlHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_RICControlHeader.DiscardUnknown(m)
}

var xxx_messageInfo_RICControlHeader proto.InternalMessageInfo

func (m *RICControlHeader) GetControlStyle() int64 {
	if m != nil {
		return m.ControlStyle
	}
	return 0
}

func (m *RICControlHeader) GetControlActionId() int64 {
	if m != nil {
		return m.ControlActionId
	}
	return 0
}

func (m *RICControlHeader) GetUEID() *UeId {
	if m != nil {
		return m.UEID
	}
	return nil
}

type UeId struct {
	GnbUEID              *GNBUEID `protobuf:"bytes,1,opt,name=GnbUEID,proto3" json:"GnbUEID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UeId) Reset()         { *m = UeId{} }
func (m *UeId) String() string { return proto.CompactTextString(m) }
func (*UeId) ProtoMessage()    {}
func (*UeId) Descriptor() ([]byte, []int) {
	return fileDescriptor_rc_15892e2b949a3eb0, []int{2}
}
func (m *UeId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UeId.Unmarshal(m, b)
}
func (m *UeId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UeId.Marshal(b, m, deterministic)
}
func (dst *UeId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UeId.Merge(dst, src)
}
func (m *UeId) XXX_Size() int {
	return xxx_messageInfo_UeId.Size(m)
}
func (m *UeId) XXX_DiscardUnknown() {
	xxx_messageInfo_UeId.DiscardUnknown(m)
}

var xxx_messageInfo_UeId proto.InternalMessageInfo

func (m *UeId) GetGnbUEID() *GNBUEID {
	if m != nil {
		return m.GnbUEID
	}
	return nil
}

type GNBUEID struct {
	AmfUENGAPID          int64    `protobuf:"varint,1,opt,name=amfUENGAPID,proto3" json:"amfUENGAPID,omitempty"`
	Guami                *Guami   `protobuf:"bytes,2,opt,name=guami,proto3" json:"guami,omitempty"`
	GNBCUUEF1APID        []int64  `protobuf:"varint,3,rep,packed,name=gNBCUUEF1APID,proto3" json:"gNBCUUEF1APID,omitempty"`
	GNBCUCPUEE1APID      []int64  `protobuf:"varint,4,rep,packed,name=gNBCUCPUEE1APID,proto3" json:"gNBCUCPUEE1APID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GNBUEID) Reset()         { *m = GNBUEID{} }
func (m *GNBUEID) String() string { return proto.CompactTextString(m) }
func (*GNBUEID) ProtoMessage()    {}
func (*GNBUEID) Descriptor() ([]byte, []int) {
	return fileDescriptor_rc_15892e2b949a3eb0, []int{3}
}
func (m *GNBUEID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GNBUEID.Unmarshal(m, b)
}
func (m *GNBUEID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GNBUEID.Marshal(b, m, deterministic)
}
func (dst *GNBUEID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GNBUEID.Merge(dst, src)
}
func (m *GNBUEID) XXX_Size() int {
	return xxx_messageInfo_GNBUEID.Size(m)
}
func (m *GNBUEID) XXX_DiscardUnknown() {
	xxx_messageInfo_GNBUEID.DiscardUnknown(m)
}

var xxx_messageInfo_GNBUEID proto.InternalMessageInfo

func (m *GNBUEID) GetAmfUENGAPID() int64 {
	if m != nil {
		return m.AmfUENGAPID
	}
	return 0
}

func (m *GNBUEID) GetGuami() *Guami {
	if m != nil {
		return m.Guami
	}
	return nil
}

func (m *GNBUEID) GetGNBCUUEF1APID() []int64 {
	if m != nil {
		return m.GNBCUUEF1APID
	}
	return nil
}

func (m *GNBUEID) GetGNBCUCPUEE1APID() []int64 {
	if m != nil {
		return m.GNBCUCPUEE1APID
	}
	return nil
}

type Guami struct {
	PLMNIdentity         string   `protobuf:"bytes,1,opt,name=pLMNIdentity,proto3" json:"pLMNIdentity,omitempty"`
	AMFRegionID          string   `protobuf:"bytes,2,opt,name=aMFRegionID,proto3" json:"aMFRegionID,omitempty"`
	AMFSetID             string   `protobuf:"bytes,3,opt,name=aMFSetID,proto3" json:"aMFSetID,omitempty"`
	AMFPointer           string   `protobuf:"bytes,4,opt,name=aMFPointer,proto3" json:"aMFPointer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Guami) Reset()         { *m = Guami{} }
func (m *Guami) String() string { return proto.CompactTextString(m) }
func (*Guami) ProtoMessage()    {}
func (*Guami) Descriptor() ([]byte, []int) {
	return fileDescriptor_rc_15892e2b949a3eb0, []int{4}
}
func (m *Guami) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Guami.Unmarshal(m, b)
}
func (m *Guami) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Guami.Marshal(b, m, deterministic)
}
func (dst *Guami) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Guami.Merge(dst, src)
}
func (m *Guami) XXX_Size() int {
	return xxx_messageInfo_Guami.Size(m)
}
func (m *Guami) XXX_DiscardUnknown() {
	xxx_messageInfo_Guami.DiscardUnknown(m)
}

var xxx_messageInfo_Guami proto.InternalMessageInfo

func (m *Guami) GetPLMNIdentity() string {
	if m != nil {
		return m.PLMNIdentity
	}
	return ""
}

func (m *Guami) GetAMFRegionID() string {
	if m != nil {
		return m.AMFRegionID
	}
	return ""
}

func (m *Guami) GetAMFSetID() string {
	if m != nil {
		return m.AMFSetID
	}
	return ""
}

func (m *Guami) GetAMFPointer() string {
	if m != nil {
		return m.AMFPointer
	}
	return ""
}

type Member struct {
	PlmnId               string   `protobuf:"bytes,1,opt,name=plmnId,proto3" json:"plmnId,omitempty"`
	Sst                  string   `protobuf:"bytes,2,opt,name=sst,proto3" json:"sst,omitempty"`
	Sd                   string   `protobuf:"bytes,3,opt,name=sd,proto3" json:"sd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Member) Reset()         { *m = Member{} }
func (m *Member) String() string { return proto.CompactTextString(m) }
func (*Member) ProtoMessage()    {}
func (*Member) Descriptor() ([]byte, []int) {
	return fileDescriptor_rc_15892e2b949a3eb0, []int{5}
}
func (m *Member) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Member.Unmarshal(m, b)
}
func (m *Member) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Member.Marshal(b, m, deterministic)
}
func (dst *Member) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Member.Merge(dst, src)
}
func (m *Member) XXX_Size() int {
	return xxx_messageInfo_Member.Size(m)
}
func (m *Member) XXX_DiscardUnknown() {
	xxx_messageInfo_Member.DiscardUnknown(m)
}

var xxx_messageInfo_Member proto.InternalMessageInfo

func (m *Member) GetPlmnId() string {
	if m != nil {
		return m.PlmnId
	}
	return ""
}

func (m *Member) GetSst() string {
	if m != nil {
		return m.Sst
	}
	return ""
}

func (m *Member) GetSd() string {
	if m != nil {
		return m.Sd
	}
	return ""
}

type Policy struct {
	Member               []*Member `protobuf:"bytes,1,rep,name=member,proto3" json:"member,omitempty"`
	MinPRB               int64     `protobuf:"varint,2,opt,name=minPRB,proto3" json:"minPRB,omitempty"`
	MaxPRB               int64     `protobuf:"varint,3,opt,name=maxPRB,proto3" json:"maxPRB,omitempty"`
	DedPRB               int64     `protobuf:"varint,4,opt,name=dedPRB,proto3" json:"dedPRB,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Policy) Reset()         { *m = Policy{} }
func (m *Policy) String() string { return proto.CompactTextString(m) }
func (*Policy) ProtoMessage()    {}
func (*Policy) Descriptor() ([]byte, []int) {
	return fileDescriptor_rc_15892e2b949a3eb0, []int{6}
}
func (m *Policy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Policy.Unmarshal(m, b)
}
func (m *Policy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Policy.Marshal(b, m, deterministic)
}
func (dst *Policy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Policy.Merge(dst, src)
}
func (m *Policy) XXX_Size() int {
	return xxx_messageInfo_Policy.Size(m)
}
func (m *Policy) XXX_DiscardUnknown() {
	xxx_messageInfo_Policy.DiscardUnknown(m)
}

var xxx_messageInfo_Policy proto.InternalMessageInfo

func (m *Policy) GetMember() []*Member {
	if m != nil {
		return m.Member
	}
	return nil
}

func (m *Policy) GetMinPRB() int64 {
	if m != nil {
		return m.MinPRB
	}
	return 0
}

func (m *Policy) GetMaxPRB() int64 {
	if m != nil {
		return m.MaxPRB
	}
	return 0
}

func (m *Policy) GetDedPRB() int64 {
	if m != nil {
		return m.DedPRB
	}
	return 0
}

type RICControlMessage struct {
	Policy               []*Policy `protobuf:"bytes,1,rep,name=policy,proto3" json:"policy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RICControlMessage) Reset()         { *m = RICControlMessage{} }
func (m *RICControlMessage) String() string { return proto.CompactTextString(m) }
func (*RICControlMessage) ProtoMessage()    {}
func (*RICControlMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_rc_15892e2b949a3eb0, []int{7}
}
func (m *RICControlMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RICControlMessage.Unmarshal(m, b)
}
func (m *RICControlMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RICControlMessage.Marshal(b, m, deterministic)
}
func (dst *RICControlMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RICControlMessage.Merge(dst, src)
}
func (m *RICControlMessage) XXX_Size() int {
	return xxx_messageInfo_RICControlMessage.Size(m)
}
func (m *RICControlMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_RICControlMessage.DiscardUnknown(m)
}

var xxx_messageInfo_RICControlMessage proto.InternalMessageInfo

func (m *RICControlMessage) GetPolicy() []*Policy {
	if m != nil {
		return m.Policy
	}
	return nil
}

// RicControl GRPC Req
type RicControlGrpcReq struct {
	E2NodeID              string             `protobuf:"bytes,1,opt,name=e2NodeID,proto3" json:"e2NodeID,omitempty"`
	PlmnID                string             `protobuf:"bytes,2,opt,name=plmnID,proto3" json:"plmnID,omitempty"`
	RanName               string             `protobuf:"bytes,3,opt,name=ranName,proto3" json:"ranName,omitempty"`
	RICE2APHeaderData     *RICE2APHeader     `protobuf:"bytes,4,opt,name=RICE2APHeaderData,proto3" json:"RICE2APHeaderData,omitempty"`
	RICControlHeaderData  *RICControlHeader  `protobuf:"bytes,5,opt,name=RICControlHeaderData,proto3" json:"RICControlHeaderData,omitempty"`
	RICControlMessageData *RICControlMessage `protobuf:"bytes,6,opt,name=RICControlMessageData,proto3" json:"RICControlMessageData,omitempty"`
	RICControlAckReqVal   RICControlAckEnum  `protobuf:"varint,7,opt,name=RICControlAckReqVal,proto3,enum=rc.RICControlAckEnum" json:"RICControlAckReqVal,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}           `json:"-"`
	XXX_unrecognized      []byte             `json:"-"`
	XXX_sizecache         int32              `json:"-"`
}

func (m *RicControlGrpcReq) Reset()         { *m = RicControlGrpcReq{} }
func (m *RicControlGrpcReq) String() string { return proto.CompactTextString(m) }
func (*RicControlGrpcReq) ProtoMessage()    {}
func (*RicControlGrpcReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_rc_15892e2b949a3eb0, []int{8}
}
func (m *RicControlGrpcReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RicControlGrpcReq.Unmarshal(m, b)
}
func (m *RicControlGrpcReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RicControlGrpcReq.Marshal(b, m, deterministic)
}
func (dst *RicControlGrpcReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RicControlGrpcReq.Merge(dst, src)
}
func (m *RicControlGrpcReq) XXX_Size() int {
	return xxx_messageInfo_RicControlGrpcReq.Size(m)
}
func (m *RicControlGrpcReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RicControlGrpcReq.DiscardUnknown(m)
}

var xxx_messageInfo_RicControlGrpcReq proto.InternalMessageInfo

func (m *RicControlGrpcReq) GetE2NodeID() string {
	if m != nil {
		return m.E2NodeID
	}
	return ""
}

func (m *RicControlGrpcReq) GetPlmnID() string {
	if m != nil {
		return m.PlmnID
	}
	return ""
}

func (m *RicControlGrpcReq) GetRanName() string {
	if m != nil {
		return m.RanName
	}
	return ""
}

func (m *RicControlGrpcReq) GetRICE2APHeaderData() *RICE2APHeader {
	if m != nil {
		return m.RICE2APHeaderData
	}
	return nil
}

func (m *RicControlGrpcReq) GetRICControlHeaderData() *RICControlHeader {
	if m != nil {
		return m.RICControlHeaderData
	}
	return nil
}

func (m *RicControlGrpcReq) GetRICControlMessageData() *RICControlMessage {
	if m != nil {
		return m.RICControlMessageData
	}
	return nil
}

func (m *RicControlGrpcReq) GetRICControlAckReqVal() RICControlAckEnum {
	if m != nil {
		return m.RICControlAckReqVal
	}
	return RICControlAckEnum_RIC_CONTROL_ACK_UNKWON
}

// RicControlGrpc Rsp
type RicControlGrpcRsp struct {
	RspCode              int32    `protobuf:"varint,1,opt,name=rspCode,proto3" json:"rspCode,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RicControlGrpcRsp) Reset()         { *m = RicControlGrpcRsp{} }
func (m *RicControlGrpcRsp) String() string { return proto.CompactTextString(m) }
func (*RicControlGrpcRsp) ProtoMessage()    {}
func (*RicControlGrpcRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_rc_15892e2b949a3eb0, []int{9}
}
func (m *RicControlGrpcRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RicControlGrpcRsp.Unmarshal(m, b)
}
func (m *RicControlGrpcRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RicControlGrpcRsp.Marshal(b, m, deterministic)
}
func (dst *RicControlGrpcRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RicControlGrpcRsp.Merge(dst, src)
}
func (m *RicControlGrpcRsp) XXX_Size() int {
	return xxx_messageInfo_RicControlGrpcRsp.Size(m)
}
func (m *RicControlGrpcRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_RicControlGrpcRsp.DiscardUnknown(m)
}

var xxx_messageInfo_RicControlGrpcRsp proto.InternalMessageInfo

func (m *RicControlGrpcRsp) GetRspCode() int32 {
	if m != nil {
		return m.RspCode
	}
	return 0
}

func (m *RicControlGrpcRsp) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*RICE2APHeader)(nil), "rc.RICE2APHeader")
	proto.RegisterType((*RICControlHeader)(nil), "rc.RICControlHeader")
	proto.RegisterType((*UeId)(nil), "rc.UeId")
	proto.RegisterType((*GNBUEID)(nil), "rc.gNBUEID")
	proto.RegisterType((*Guami)(nil), "rc.Guami")
	proto.RegisterType((*Member)(nil), "rc.Member")
	proto.RegisterType((*Policy)(nil), "rc.Policy")
	proto.RegisterType((*RICControlMessage)(nil), "rc.RICControlMessage")
	proto.RegisterType((*RicControlGrpcReq)(nil), "rc.RicControlGrpcReq")
	proto.RegisterType((*RicControlGrpcRsp)(nil), "rc.RicControlGrpcRsp")
	proto.RegisterEnum("rc.RICControlCellTypeEnum", RICControlCellTypeEnum_name, RICControlCellTypeEnum_value)
	proto.RegisterEnum("rc.RICControlAckEnum", RICControlAckEnum_name, RICControlAckEnum_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgCommClient is the client API for MsgComm service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgCommClient interface {
	// gRPC call to Send RICControlReqServiceGrpc
	SendRICControlReqServiceGrpc(ctx context.Context, in *RicControlGrpcReq, opts ...grpc.CallOption) (*RicControlGrpcRsp, error)
}

type msgCommClient struct {
	cc *grpc.ClientConn
}

func NewMsgCommClient(cc *grpc.ClientConn) MsgCommClient {
	return &msgCommClient{cc}
}

func (c *msgCommClient) SendRICControlReqServiceGrpc(ctx context.Context, in *RicControlGrpcReq, opts ...grpc.CallOption) (*RicControlGrpcRsp, error) {
	out := new(RicControlGrpcRsp)
	err := c.cc.Invoke(ctx, "/rc.MsgComm/SendRICControlReqServiceGrpc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgCommServer is the server API for MsgComm service.
type MsgCommServer interface {
	// gRPC call to Send RICControlReqServiceGrpc
	SendRICControlReqServiceGrpc(context.Context, *RicControlGrpcReq) (*RicControlGrpcRsp, error)
}

func RegisterMsgCommServer(s *grpc.Server, srv MsgCommServer) {
	s.RegisterService(&_MsgComm_serviceDesc, srv)
}

func _MsgComm_SendRICControlReqServiceGrpc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RicControlGrpcReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgCommServer).SendRICControlReqServiceGrpc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rc.MsgComm/SendRICControlReqServiceGrpc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgCommServer).SendRICControlReqServiceGrpc(ctx, req.(*RicControlGrpcReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _MsgComm_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rc.MsgComm",
	HandlerType: (*MsgCommServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendRICControlReqServiceGrpc",
			Handler:    _MsgComm_SendRICControlReqServiceGrpc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rc.proto",
}

func init() { proto.RegisterFile("rc.proto", fileDescriptor_rc_15892e2b949a3eb0) }

var fileDescriptor_rc_15892e2b949a3eb0 = []byte{
	// 763 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x95, 0x4b, 0x6f, 0xda, 0x40,
	0x10, 0xc7, 0x6b, 0xcc, 0x23, 0x0c, 0x4d, 0x42, 0x36, 0x2f, 0x94, 0x46, 0x2d, 0xb2, 0xda, 0x0a,
	0x45, 0x6a, 0xa4, 0xd2, 0x43, 0x8f, 0x15, 0x38, 0x86, 0x58, 0x01, 0x83, 0x86, 0xb8, 0x39, 0x46,
	0x8e, 0xbd, 0x45, 0x56, 0xf0, 0x03, 0xdb, 0x54, 0xe5, 0xd2, 0x43, 0x6f, 0xfd, 0x0e, 0xfd, 0xb0,
	0xd5, 0xae, 0x17, 0x0c, 0x0e, 0x37, 0xe6, 0x37, 0x33, 0xff, 0x99, 0x1d, 0xcf, 0x2e, 0xb0, 0x17,
	0xd9, 0xd7, 0x61, 0x14, 0x24, 0x01, 0x29, 0x44, 0xb6, 0x62, 0xc2, 0x3e, 0xea, 0xaa, 0xd6, 0xee,
	0x8c, 0x6f, 0xa9, 0xe5, 0xd0, 0x88, 0x5c, 0x42, 0x15, 0x2d, 0xbf, 0xb7, 0xf0, 0x6d, 0xdd, 0x69,
	0x48, 0x4d, 0xa9, 0x25, 0x63, 0x06, 0xc8, 0x47, 0x38, 0x40, 0x5d, 0x45, 0x3a, 0x5f, 0xd0, 0x38,
	0x09, 0x22, 0xfd, 0xa6, 0x51, 0xe0, 0x21, 0x39, 0xaa, 0xfc, 0x86, 0x3a, 0xea, 0xaa, 0x1a, 0xf8,
	0x49, 0x14, 0xcc, 0x84, 0xb2, 0x02, 0xaf, 0x05, 0x98, 0x24, 0xcb, 0x19, 0x15, 0xe2, 0x5b, 0x8c,
	0xb4, 0xe0, 0x50, 0xd8, 0x1d, 0x3b, 0x71, 0x03, 0x5f, 0x77, 0x44, 0x81, 0x3c, 0x26, 0x97, 0x50,
	0x34, 0x35, 0xfd, 0xa6, 0x21, 0x37, 0xa5, 0x56, 0xad, 0xbd, 0x77, 0x1d, 0xd9, 0xd7, 0x26, 0xd5,
	0x1d, 0xe4, 0x54, 0xf9, 0x04, 0x45, 0x66, 0x91, 0x0f, 0x50, 0xe9, 0xfb, 0x4f, 0x3c, 0x50, 0xe2,
	0x81, 0x35, 0x16, 0x38, 0x35, 0xba, 0x0c, 0xe1, 0xca, 0xa7, 0xfc, 0x93, 0xa0, 0x22, 0x20, 0x69,
	0x42, 0xcd, 0xf2, 0x7e, 0x98, 0x9a, 0xd1, 0xef, 0x8c, 0x45, 0x9a, 0x8c, 0x9b, 0x88, 0xbc, 0x83,
	0xd2, 0x74, 0x61, 0x79, 0x2e, 0x6f, 0xad, 0xd6, 0xae, 0x32, 0xc9, 0x3e, 0x03, 0x98, 0x72, 0xf2,
	0x1e, 0xf6, 0xa7, 0x46, 0x57, 0x35, 0x4d, 0xad, 0xf7, 0x99, 0x8b, 0xc8, 0x4d, 0xb9, 0x25, 0xe3,
	0x36, 0x64, 0x67, 0xe5, 0x40, 0x1d, 0x9b, 0x9a, 0x96, 0xc6, 0x15, 0x79, 0x5c, 0x1e, 0x2b, 0x7f,
	0x25, 0x28, 0xf1, 0x02, 0x6c, 0x86, 0xe1, 0x60, 0x68, 0xe8, 0x0e, 0xf5, 0x13, 0x37, 0x59, 0xf2,
	0xee, 0xaa, 0xb8, 0xc5, 0xf8, 0x01, 0x86, 0x3d, 0xa4, 0x53, 0x36, 0xa8, 0xf4, 0x03, 0x55, 0x71,
	0x13, 0x91, 0x0b, 0xd8, 0xb3, 0x86, 0xbd, 0x09, 0x4d, 0xc4, 0xfc, 0xaa, 0xb8, 0xb6, 0xc9, 0x5b,
	0x00, 0x6b, 0xd8, 0x1b, 0x07, 0xae, 0x9f, 0xd0, 0xa8, 0x51, 0xe4, 0xde, 0x0d, 0xa2, 0x74, 0xa1,
	0x3c, 0xa4, 0xde, 0x13, 0x8d, 0xc8, 0x19, 0x94, 0xc3, 0x99, 0xe7, 0x8b, 0x35, 0xa9, 0xa2, 0xb0,
	0x48, 0x1d, 0xe4, 0x38, 0x4e, 0x44, 0x5d, 0xf6, 0x93, 0x1c, 0x40, 0x21, 0x76, 0x44, 0xa5, 0x42,
	0xec, 0x28, 0x09, 0x94, 0xc7, 0xc1, 0xcc, 0xb5, 0x97, 0x44, 0x81, 0xb2, 0xc7, 0xd5, 0x1a, 0x52,
	0x53, 0x6e, 0xd5, 0xda, 0xc0, 0x66, 0x99, 0xea, 0xa3, 0xf0, 0xb0, 0x3a, 0x9e, 0xeb, 0x8f, 0xb1,
	0x2b, 0x56, 0x41, 0x58, 0x9c, 0x5b, 0xbf, 0x18, 0x97, 0x05, 0xe7, 0x16, 0xe3, 0x0e, 0x75, 0x18,
	0x2f, 0xa6, 0x3c, 0xb5, 0x94, 0xaf, 0x70, 0x94, 0xed, 0xe4, 0x90, 0xc6, 0xb1, 0x35, 0xa5, 0xac,
	0x81, 0x90, 0xb7, 0xb2, 0xd9, 0x40, 0xda, 0x1c, 0x0a, 0x8f, 0xf2, 0x47, 0x86, 0x23, 0x74, 0x6d,
	0x91, 0xd9, 0x8f, 0x42, 0x1b, 0xe9, 0x9c, 0x0d, 0x91, 0xb6, 0x8d, 0xc0, 0xa1, 0x62, 0x49, 0xaa,
	0xb8, 0xb6, 0xd7, 0xa3, 0x59, 0x4d, 0x5f, 0x58, 0xa4, 0x01, 0x95, 0xc8, 0xf2, 0x0d, 0xcb, 0xa3,
	0x62, 0x1a, 0x2b, 0x93, 0x7c, 0xe3, 0xcd, 0x65, 0xf7, 0xf0, 0xc6, 0x4a, 0x2c, 0xde, 0x7f, 0xad,
	0x7d, 0xc4, 0x5a, 0xda, 0x72, 0xe2, 0xcb, 0x58, 0x72, 0x0b, 0x27, 0xf9, 0x1b, 0xc7, 0x35, 0x4a,
	0x5c, 0xe3, 0x44, 0x68, 0x6c, 0xf9, 0x71, 0x67, 0x06, 0xb9, 0x83, 0xd3, 0x17, 0x73, 0xe2, 0x52,
	0x65, 0x2e, 0x75, 0xba, 0x2d, 0x25, 0x02, 0x70, 0x77, 0x0e, 0xe9, 0xc3, 0x71, 0xe6, 0xe8, 0xd8,
	0xcf, 0x48, 0xe7, 0xdf, 0xad, 0x59, 0xa3, 0xd2, 0x94, 0x5a, 0x07, 0x79, 0xa9, 0x8e, 0xfd, 0xac,
	0xf9, 0x0b, 0x0f, 0x77, 0x65, 0x28, 0xa3, 0x17, 0xdf, 0x20, 0x0e, 0xf9, 0x3c, 0xe3, 0x50, 0x0d,
	0x9c, 0xf4, 0x35, 0x29, 0xe1, 0xca, 0x64, 0x97, 0xc0, 0xa1, 0xb1, 0x1d, 0xb9, 0x21, 0x7b, 0x2f,
	0x56, 0x97, 0x60, 0x03, 0x5d, 0x3d, 0xc3, 0x59, 0x56, 0x47, 0xa5, 0xb3, 0xd9, 0xfd, 0x32, 0xa4,
	0xac, 0x3e, 0x79, 0x03, 0xe7, 0xa8, 0xab, 0x8f, 0xea, 0xc8, 0xb8, 0xc7, 0xd1, 0xe0, 0x51, 0xd5,
	0x06, 0x83, 0x47, 0xd3, 0xb8, 0x7b, 0x18, 0x19, 0xf5, 0x57, 0xe4, 0x9c, 0x1f, 0x68, 0xed, 0x34,
	0x90, 0xfb, 0xeb, 0x52, 0x3e, 0x4b, 0x33, 0xef, 0xb1, 0x63, 0xa4, 0xce, 0xc2, 0x55, 0xb4, 0xb9,
	0x7b, 0xe2, 0x9c, 0xe4, 0x82, 0x77, 0xb0, 0xce, 0xe8, 0xa8, 0x77, 0x59, 0x99, 0x33, 0x20, 0x5b,
	0x65, 0x46, 0xcc, 0x5d, 0x97, 0xc8, 0x31, 0x1c, 0xe6, 0x72, 0xea, 0x05, 0x72, 0xc2, 0x5f, 0xdb,
	0x2c, 0x98, 0x51, 0xb9, 0xfd, 0x00, 0x95, 0x61, 0x3c, 0x55, 0x03, 0xcf, 0x23, 0x03, 0xb8, 0x9c,
	0x50, 0xdf, 0xc9, 0x5a, 0x40, 0x3a, 0x9f, 0xd0, 0xe8, 0xa7, 0x6b, 0x53, 0x36, 0x4a, 0x92, 0x7e,
	0x88, 0xfc, 0x8a, 0x5f, 0xec, 0xc2, 0x71, 0xf8, 0x54, 0xe6, 0x7f, 0x1f, 0x5f, 0xfe, 0x07, 0x00,
	0x00, 0xff, 0xff, 0xf1, 0x9e, 0x4b, 0xc3, 0x4a, 0x06, 0x00, 0x00,
}
